spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news-api
    username: postgres
    password: postgres
    hikari:
      schema: news_schema

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

